### ISSUE TITLE
FrameCropper - DetectionBoxes are None

### ISSUE THREAD

**Issue by Jan-t2b-filip** [ChlupacTheBosmer/DetectFlow#1]
07/09/2024 15:18:32 - INFO - root -   Running smart_crop()
07/09/2024 15:18:32 - INFO - root -   Subcroping image
07/09/2024 15:18:32 - INFO - root -   Running subcrop()
07/09/2024 15:18:32 - ERROR - root -   ERROR: unsupported operand type(s) for *: 'int' and 'NoneType' /storage/brno2/home/filipja2/day_slice_1/object/0.3/SAK1_K5_HibEng2_20221205_08_07_6847.png, detectflow.predict.results.DetectionBoxes object with attributes:

cls: None
coco: array([[         37,         382,         909,         693]])
conf: None
data: array([[         37,         382,         946,        1075]])
id: None
is_track: False
orig_shape: (1080, 1488)
shape: (1, 4)
xywh: array([[      491.5,       728.5,         909,         693]])
xywhn: array([[    0.33031,     0.67454,     0.61089,     0.64167]])
xyxy: array([[         37,         382,         946,        1075]])
xyxyn: array([[   0.024866,      0.3537,     0.63575,     0.99537]])
Traceback (most recent call last):
  File "/auto/brno2/home/filipja2/onboarding/DetectFlow/detectflow/image/smart_crop.py", line 441, in process_image
    crop_result = smart_crop.smart_crop(
  File "/auto/brno2/home/filipja2/onboarding/DetectFlow/detectflow/image/smart_crop.py", line 351, in smart_crop
    return self.subcrop(aspect_ratio=self.crop_aspect_ratio, inspect=inspect)
  File "/auto/brno2/home/filipja2/onboarding/DetectFlow/detectflow/image/smart_crop.py", line 265, in subcrop
    roi_size = FrameManipulator.calculate_largest_roi(self.image_size, aspect_ratio)
  File "/auto/brno2/home/filipja2/onboarding/DetectFlow/detectflow/manipulators/frame_manipulator.py", line 321, in calculate_largest_roi
    possible_width = img_height * target_aspect_ratio
TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'

07/09/2024 15:26:35 - ERROR - root -   ERROR: object of type 'NoneType' has no len() /storage/brno2/home/filipja2/day_slice_1/object/0.3/CZ2_M2_TriCam03_20210616_16_21_10365.png, detectflow.predict.results.DetectionBoxes object with attributes:

cls: None
coco: array([[        732,         457,         108,         130],
       [        510,         365,          85,          73],
       [        380,         231,      93.001,          89],
       [        408,      56.001,          84,          89],
       [        238,         105,          85,          66],
       [    -42.999,    -0.00054,          78,          71],
       [        705,         765,         105,         100],
       [        772,         804,      98.001,         108],
       [        905,         892,          90,          95],
       [        890,         600,      86.999,          97],
       [        969,         600,          91,         113],
       [        974,         183,          90,          95],
       [       1159,          85,         103,         113],
       [       1517,         108,         114,         130],
       [       1506,         288,         125,         140],
       [       1362,         490,          79,          80],
       [       1451,         678,         107,         114],
       [       1281,         830,      87.999,          79],
       [       1736,         917,      92.001,          70],
       [       1854,      61.001,          97,         104]])
conf: None
data: array([[        732,         457,         840,         587],
       [        510,         365,         595,         438],
       [        380,         231,         473,         320],
       [        408,      56.001,         492,         145],
       [        238,         105,         323,         171],
       [    -42.999,    -0.00054,      35.001,          71],
       [        705,         765,         810,         865],
       [        772,         804,         870,         912],
       [        905,         892,         995,         987],
       [        890,         600,         977,         697],
       [        969,         600,        1060,         713],
       [        974,         183,        1064,         278],
       [       1159,          85,        1262,         198],
       [       1517,         108,        1631,         238],
       [       1506,         288,        1631,         428],
       [       1362,         490,        1441,         570],
       [       1451,         678,        1558,         792],
       [       1281,         830,        1369,         909],
       [       1736,         917,        1828,         987],
       [       1854,      61.001,        1951,         165]])
id: None
is_track: False
orig_shape: (1080, 1920)
shape: (20, 4)
xywh: array([[        786,         522,         108,         130],
       [      552.5,       401.5,          85,          73],
       [      426.5,       275.5,      93.001,          89],
       [        450,       100.5,          84,          89],
       [      280.5,         138,          85,          66],
       [    -3.9994,        35.5,          78,          71],
       [      757.5,         815,         105,         100],
       [        821,         858,      98.001,         108],
       [        950,       939.5,          90,          95],
       [      933.5,       648.5,      86.999,          97],
       [     1014.5,       656.5,          91,         113],
       [       1019,       230.5,          90,          95],
       [     1210.5,       141.5,         103,         113],
       [       1574,         173,         114,         130],
       [     1568.5,         358,         125,         140],
       [     1401.5,         530,          79,          80],
       [     1504.5,         735,         107,         114],
       [       1325,       869.5,      87.999,          79],
       [       1782,         952,      92.001,          70],
       [     1902.5,         113,          97,         104]])
xywhn: array([[    0.40937,     0.48333,     0.05625,     0.12037],
       [    0.28776,     0.37176,    0.044271,    0.067593],
       [    0.22213,     0.25509,    0.048438,    0.082407],
       [    0.23438,    0.093056,     0.04375,    0.082407],
       [    0.14609,     0.12778,    0.044271,    0.061111],
       [  -0.002083,     0.03287,    0.040625,    0.065741],
       [    0.39453,     0.75463,    0.054688,    0.092593],
       [     0.4276,     0.79444,    0.051042,         0.1],
       [    0.49479,     0.86991,    0.046875,    0.087963],
       [     0.4862,     0.60046,    0.045312,    0.089815],
       [    0.52838,     0.60787,    0.047396,     0.10463],
       [    0.53073,     0.21343,    0.046875,    0.087963],
       [    0.63047,     0.13102,    0.053646,     0.10463],
       [    0.81979,     0.16018,    0.059375,     0.12037],
       [    0.81693,     0.33148,    0.065104,     0.12963],
       [    0.72995,     0.49074,    0.041146,    0.074074],
       [    0.78359,     0.68056,    0.055729,     0.10556],
       [     0.6901,     0.80509,    0.045833,    0.073148],
       [    0.92812,     0.88148,    0.047917,    0.064815],
       [    0.99088,     0.10463,    0.050521,    0.096296]])
xyxy: array([[        732,         457,         840,         587],
       [        510,         365,         595,         438],
       [        380,         231,         473,         320],
       [        408,      56.001,         492,         145],
       [        238,         105,         323,         171],
       [    -42.999,    -0.00054,      35.001,          71],
       [        705,         765,         810,         865],
       [        772,         804,         870,         912],
       [        905,         892,         995,         987],
       [        890,         600,         977,         697],
       [        969,         600,        1060,         713],
       [        974,         183,        1064,         278],
       [       1159,          85,        1262,         198],
       [       1517,         108,        1631,         238],
       [       1506,         288,        1631,         428],
       [       1362,         490,        1441,         570],
       [       1451,         678,        1558,         792],
       [       1281,         830,        1369,         909],
       [       1736,         917,        1828,         987],
       [       1854,      61.001,        1951,         165]])
xyxyn: array([[    0.38125,     0.42315,      0.4375,     0.54352],
       [    0.26562,     0.33796,      0.3099,     0.40556],
       [    0.19792,     0.21389,     0.24635,      0.2963],
       [     0.2125,    0.051853,     0.25625,     0.13426],
       [    0.12396,    0.097223,     0.16823,     0.15833],
       [  -0.022396,      -5e-07,    0.018229,    0.065741],
       [    0.36719,     0.70833,     0.42188,     0.80093],
       [    0.40208,     0.74444,     0.45312,     0.84444],
       [    0.47135,     0.82593,     0.51823,     0.91389],
       [    0.46354,     0.55556,     0.50885,     0.64537],
       [    0.50469,     0.55556,     0.55208,     0.66019],
       [    0.50729,     0.16944,     0.55417,     0.25741],
       [    0.60365,    0.078704,     0.65729,     0.18333],
       [     0.7901,         0.1,     0.84948,     0.22037],
       [    0.78437,     0.26667,     0.84948,      0.3963],
       [    0.70938,      0.4537,     0.75052,     0.52778],
       [    0.75573,     0.62778,     0.81146,     0.73333],
       [    0.66719,     0.76852,     0.71302,     0.84167],
       [    0.90417,     0.84907,     0.95208,     0.91389],
       [    0.96562,    0.056482,      1.0161,     0.15278]])
Traceback (most recent call last):
  File "/auto/brno2/home/filipja2/onboarding/DetectFlow/detectflow/image/smart_crop.py", line 441, in process_image
    crop_result = smart_crop.smart_crop(
  File "/auto/brno2/home/filipja2/onboarding/DetectFlow/detectflow/image/smart_crop.py", line 371, in smart_crop
    return self.crop(inspect=inspect,
  File "/auto/brno2/home/filipja2/onboarding/DetectFlow/detectflow/image/smart_crop.py", line 72, in crop
    rois = BoxManipulator.get_optimal_roi(self.annotations, self.image_size, crop_size, handle_overflow,
  File "/auto/brno2/home/filipja2/onboarding/DetectFlow/detectflow/manipulators/box_manipulator.py", line 375, in get_optimal_roi
    while len(remaining_boxes) > 0:
TypeError: object of type 'NoneType' has no len()

**Comment by ChlupacTheBosmer** [comment]
Fixed remaining boxes check
